from enum import Enum


class FaultType(str, Enum):
    SENSOR_UNAVAILABLE = "SENSOR_UNAVAILABLE"
    SENSOR_TIMEOUT = "SENSOR_TIMEOUT"
    INVALID_SENSOR_READING = "INVALID_SENSOR_READING"
    MOTOR_COMMAND_INVALID = "MOTOR_COMMAND_INVALID"
    MOTOR_CONTROLLER_FAULT = "MOTOR_CONTROLLER_FAULT"
